name: Deploy Frappe Apps

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: 'App to deploy (e.g., public_app_1, private_app_2)'
        required: true
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'
      commit_id:
        description: 'Commit ID (optional, for rollback or specific deployment)'
        required: false
      site_name:
        description: 'Site to deploy (Required)'
        required: true  # Now, site_name is mandatory

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to Server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /home/frappe/ci_cd
          ./deploy.sh ${{ inputs.app_name }} ${{ inputs.branch }} ${{ inputs.commit_id }} ${{ inputs.site_name }}

    - name: Post-Deployment Health Check (Frappe API)
      run: |
        sleep 10  # Wait for the server to restart
        FRAPPE_URL="https://${{ inputs.site_name }}/api/method/frappe.handler.ping"
        echo "Checking Frappe site health after deployment at: $FRAPPE_URL"

        RESPONSE=$(curl -s "$FRAPPE_URL")
        echo "Response: $RESPONSE"

        if [[ "$RESPONSE" != "\"pong\"" ]]; then
          echo "Deployment failed! Site is unhealthy."
          exit 1
        fi
        echo "Deployment successful. Site is running fine."
